From the `Bamboo_setup` directory, run the following command:
```bash
jupyter notebook --no-browser --port=8888
```
Copy the URL starting with `http://localhost:8888/`.
When picking the kernel for this notebook, click **Existing Jupyter Server** and paste the URL.

In [2]:
Z_OUTPUT_eos = Path('/eos/user/a/anunezde/Z_OUTPUT_eos')
WORKDIR = Z_OUTPUT_eos / '2022_even_0822' / 'LLR_and_vars_4o5'
sel_name = 'SL_res_2b_x'
total_inputs = 'input/8llrs1D.txt'

# Setup a data handler

In [3]:
from post_processing.NN.DataHandler import DataHandler
datahandler = DataHandler(workdir=WORKDIR.resolve(), tree_name=sel_name, total_inputs=total_inputs)
total_df = datahandler.load_data()
total_df = datahandler.fix_any_mismatch(total_df)
total_df

Welcome to JupyROOT 6.30/02
	Loading data ...

            event     genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr          File  Process
186577         18      3.805950        -0.278           0.401           0.742         1.496          1.167    0.428            0.439              0.014  tbarWplus_dl       tW
13167          32      0.033119        -0.242           0.329           0.937         1.507          0.849    0.393            0.549              1.259       bbWW_sl  HH_bbWW
706510         36     81.103897        -0.322          -0.791          -1.330        -2.183         -2.512   -0.028            0.317             -0.649      TTbar_dl    ttbar
13168          42      0.033119         0.132           0.239           1.084         1.504          0.714    0.130            0.117             -0.098       bbWW_sl  HH_bbWW
11905          58      0.033119         0.109           0.358           0.747         1.493          1.051   -0.491            0.396             -0.674       bbWW_dl  HH_bbWW
...           ...           ...           ...             ...             ...           ...            ...      ...              ...                ...           ...      ...
30323   744899478  83745.546875        -0.288           0.327          -0.377        -0.090         -0.269   -0.151           -0.445             -0.622      Wjets_2J    WJets
30340   745108688  83745.546875        -0.223           0.343           0.757         1.520          0.263    0.193            0.558             -0.775      Wjets_2J    WJets
30318   745244862  83745.546875        -0.219             NaN           0.886        -1.550           -inf   -0.071           -1.004              0.563      Wjets_2J    WJets
30006   745282826 -83745.546875        -0.325          -0.230           0.668        -0.090          0.155   -0.419           -0.551             -0.246      Wjets_2J    WJets
30007   745344992  83745.546875        -0.233           0.312           0.284        -1.004         -1.397    0.002           -0.136             -0.571      Wjets_2J    WJets

[1900341 rows x 12 columns]

In [4]:
def check(df):
    # For np.nan
    nan_cells = df.isna().sum().sum()
    neg_9999_cells = (df == -9999).sum().sum()
    neg_9_cells = (df == -9).sum().sum()
    pos_9999_cells = (df == 9999).sum().sum()

    print(f"Number of cells with NaN: {nan_cells}")
    print(f"Number of cells with -9999: {neg_9999_cells}")
    print(f"Number of cells with -9: {neg_9_cells}")
    print(f"Number of cells with +9999: {pos_9999_cells}")

In [5]:
preprocessed_df = datahandler.preprocess_data(total_df, nan_replacement = -9999)

Preprocessing data ...
After removing events with negative weights:
LLRs were found in the loaded data.
Replacing nan values with -9999
Total_df:
            event     genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr          File  Process_DY  Process_HH_bbWW  Process_HH_bbtautau  Process_VV  Process_WJets  Process_tW  Process_ttbar
186577         18      3.805950        -0.278           0.401           0.742         1.496          1.167    0.428            0.439              0.014  tbarWplus_dl           0                0                    0           0              0           1              0
13167          32      0.033119        -0.242           0.329           0.937         1.507          0.849    0.393            0.549              1.259       bbWW_sl           0                1                    0           0              0           0              0
706510         36     81.103897        -0.322          -0.791          -1.330        -2.183         -2.512   -0.028            0.317             -0.649      TTbar_dl           0                0                    0           0              0           0              1
13168          42      0.033119         0.132           0.239           1.084         1.504          0.714    0.130            0.117             -0.098       bbWW_sl           0                1                    0           0              0           0              0
11905          58      0.033119         0.109           0.358           0.747         1.493          1.051   -0.491            0.396             -0.674       bbWW_dl           0                1                    0           0              0           0              0
...           ...           ...           ...             ...             ...           ...            ...      ...              ...                ...           ...         ...              ...                  ...         ...            ...         ...            ...
29962   744617994  83745.546875        -0.275          -1.727          -1.356        -1.671          0.849   -0.132            0.368             -0.112      Wjets_2J           0                0                    0           0              1           0              0
30323   744899478  83745.546875        -0.288           0.327          -0.377        -0.090         -0.269   -0.151           -0.445             -0.622      Wjets_2J           0                0                    0           0              1           0              0
30340   745108688  83745.546875        -0.223           0.343           0.757         1.520          0.263    0.193            0.558             -0.775      Wjets_2J           0                0                    0           0              1           0              0
30318   745244862  83745.546875        -0.219       -9999.000           0.886        -1.550        -20.000   -0.071           -1.004              0.563      Wjets_2J           0                0                    0           0              1           0              0
30007   745344992  83745.546875        -0.233           0.312           0.284        -1.004         -1.397    0.002           -0.136             -0.571      Wjets_2J           0                0                    0           0              1           0              0

[1878383 rows x 18 columns]

In [6]:
preprocessed_df_v2 = datahandler.preprocess_data(total_df, nan_replacement = -9)

Preprocessing data ...
After removing events with negative weights:
LLRs were found in the loaded data.
Replacing nan values with -9
Total_df:
            event     genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr          File  Process_DY  Process_HH_bbWW  Process_HH_bbtautau  Process_VV  Process_WJets  Process_tW  Process_ttbar
186577         18      3.805950        -0.278           0.401           0.742         1.496          1.167    0.428            0.439              0.014  tbarWplus_dl           0                0                    0           0              0           1              0
13167          32      0.033119        -0.242           0.329           0.937         1.507          0.849    0.393            0.549              1.259       bbWW_sl           0                1                    0           0              0           0              0
706510         36     81.103897        -0.322          -0.791          -1.330        -2.183         -2.512   -0.028            0.317             -0.649      TTbar_dl           0                0                    0           0              0           0              1
13168          42      0.033119         0.132           0.239           1.084         1.504          0.714    0.130            0.117             -0.098       bbWW_sl           0                1                    0           0              0           0              0
11905          58      0.033119         0.109           0.358           0.747         1.493          1.051   -0.491            0.396             -0.674       bbWW_dl           0                1                    0           0              0           0              0
...           ...           ...           ...             ...             ...           ...            ...      ...              ...                ...           ...         ...              ...                  ...         ...            ...         ...            ...
29962   744617994  83745.546875        -0.275          -1.727          -1.356        -1.671          0.849   -0.132            0.368             -0.112      Wjets_2J           0                0                    0           0              1           0              0
30323   744899478  83745.546875        -0.288           0.327          -0.377        -0.090         -0.269   -0.151           -0.445             -0.622      Wjets_2J           0                0                    0           0              1           0              0
30340   745108688  83745.546875        -0.223           0.343           0.757         1.520          0.263    0.193            0.558             -0.775      Wjets_2J           0                0                    0           0              1           0              0
30318   745244862  83745.546875        -0.219          -9.000           0.886        -1.550        -20.000   -0.071           -1.004              0.563      Wjets_2J           0                0                    0           0              1           0              0
30007   745344992  83745.546875        -0.233           0.312           0.284        -1.004         -1.397    0.002           -0.136             -0.571      Wjets_2J           0                0                    0           0              1           0              0

[1878383 rows x 18 columns]

In [7]:
preprocessed_df_v3 = datahandler.preprocess_data(total_df, nan_replacement = 9999)

Preprocessing data ...
After removing events with negative weights:
LLRs were found in the loaded data.
Replacing nan values with 9999
Total_df:
            event     genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr          File  Process_DY  Process_HH_bbWW  Process_HH_bbtautau  Process_VV  Process_WJets  Process_tW  Process_ttbar
186577         18      3.805950        -0.278           0.401           0.742         1.496          1.167    0.428            0.439              0.014  tbarWplus_dl           0                0                    0           0              0           1              0
13167          32      0.033119        -0.242           0.329           0.937         1.507          0.849    0.393            0.549              1.259       bbWW_sl           0                1                    0           0              0           0              0
706510         36     81.103897        -0.322          -0.791          -1.330        -2.183         -2.512   -0.028            0.317             -0.649      TTbar_dl           0                0                    0           0              0           0              1
13168          42      0.033119         0.132           0.239           1.084         1.504          0.714    0.130            0.117             -0.098       bbWW_sl           0                1                    0           0              0           0              0
11905          58      0.033119         0.109           0.358           0.747         1.493          1.051   -0.491            0.396             -0.674       bbWW_dl           0                1                    0           0              0           0              0
...           ...           ...           ...             ...             ...           ...            ...      ...              ...                ...           ...         ...              ...                  ...         ...            ...         ...            ...
29962   744617994  83745.546875        -0.275          -1.727          -1.356        -1.671          0.849   -0.132            0.368             -0.112      Wjets_2J           0                0                    0           0              1           0              0
30323   744899478  83745.546875        -0.288           0.327          -0.377        -0.090         -0.269   -0.151           -0.445             -0.622      Wjets_2J           0                0                    0           0              1           0              0
30340   745108688  83745.546875        -0.223           0.343           0.757         1.520          0.263    0.193            0.558             -0.775      Wjets_2J           0                0                    0           0              1           0              0
30318   745244862  83745.546875        -0.219        9999.000           0.886        -1.550        -20.000   -0.071           -1.004              0.563      Wjets_2J           0                0                    0           0              1           0              0
30007   745344992  83745.546875        -0.233           0.312           0.284        -1.004         -1.397    0.002           -0.136             -0.571      Wjets_2J           0                0                    0           0              1           0              0

[1878383 rows x 18 columns]

In [103]:
import numpy as np
preprocessed_df_v4 = datahandler.preprocess_data(total_df, nan_replacement = np.nan)

Preprocessing data ...
After removing events with negative weights:
LLRs were found in the loaded data.
Replacing nan values with nan
Total_df:
            event     genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr          File  Process_DY  Process_HH_bbWW  Process_HH_bbtautau  Process_VV  Process_WJets  Process_tW  Process_ttbar
186577         18      3.805950        -0.278           0.401           0.742         1.496          1.167    0.428            0.439              0.014  tbarWplus_dl           0                0                    0           0              0           1              0
13167          32      0.033119        -0.242           0.329           0.937         1.507          0.849    0.393            0.549              1.259       bbWW_sl           0                1                    0           0              0           0              0
706510         36     81.103897        -0.322          -0.791          -1.330        -2.183         -2.512   -0.028            0.317             -0.649      TTbar_dl           0                0                    0           0              0           0              1
13168          42      0.033119         0.132           0.239           1.084         1.504          0.714    0.130            0.117             -0.098       bbWW_sl           0                1                    0           0              0           0              0
11905          58      0.033119         0.109           0.358           0.747         1.493          1.051   -0.491            0.396             -0.674       bbWW_dl           0                1                    0           0              0           0              0
...           ...           ...           ...             ...             ...           ...            ...      ...              ...                ...           ...         ...              ...                  ...         ...            ...         ...            ...
29962   744617994  83745.546875        -0.275          -1.727          -1.356        -1.671          0.849   -0.132            0.368             -0.112      Wjets_2J           0                0                    0           0              1           0              0
30323   744899478  83745.546875        -0.288           0.327          -0.377        -0.090         -0.269   -0.151           -0.445             -0.622      Wjets_2J           0                0                    0           0              1           0              0
30340   745108688  83745.546875        -0.223           0.343           0.757         1.520          0.263    0.193            0.558             -0.775      Wjets_2J           0                0                    0           0              1           0              0
30318   745244862  83745.546875        -0.219             NaN           0.886        -1.550        -20.000   -0.071           -1.004              0.563      Wjets_2J           0                0                    0           0              1           0              0
30007   745344992  83745.546875        -0.233           0.312           0.284        -1.004         -1.397    0.002           -0.136             -0.571      Wjets_2J           0                0                    0           0              1           0              0

[1878383 rows x 18 columns]

# Inspect preprocessing

In [102]:
check(total_df)

Number of cells with NaN: 44138
Number of cells with -9999: 0
Number of cells with -9: 0
Number of cells with +9999: 0

In [9]:
check(preprocessed_df)

Number of cells with NaN: 0
Number of cells with -9999: 43487
Number of cells with -9: 0
Number of cells with +9999: 0

In [10]:
check(preprocessed_df_v2)

Number of cells with NaN: 0
Number of cells with -9999: 0
Number of cells with -9: 43487
Number of cells with +9999: 0

In [11]:
check(preprocessed_df_v3)

Number of cells with NaN: 0
Number of cells with -9999: 0
Number of cells with -9: 0
Number of cells with +9999: 43487

In [96]:
check(preprocessed_df_v4)

Number of cells with NaN: 43487
Number of cells with -9999: 0
Number of cells with -9: 0
Number of cells with +9999: 0

# DNNModel

In [97]:
import post_processing.NN.model_builder as model_builder
from tensorflow.keras.layers import Input, BatchNormalization, Dense, Normalization, Activation, Dropout, Masking, Add
from tensorflow.keras import Model

from tensorflow.keras.initializers import RandomNormal

initializer = RandomNormal(mean=0, stddev=1)

def setup_architecture_from_yml(config, input_layer, normalized_input):
    print(f"\t\tSetting up architecture from yml ...")
    print(f"\t\tTesting without BN ...")
    print(f"\t\tWith RN now ...")
    x = normalized_input
    for n_layer, layer in enumerate(config.hiddenlayers):
        if layer.type == 'Dense':
            reg = model_builder.get_activity_regularizer(layer.act_regularizer)
            if config.residual_network:
                if n_layer == 0:
                    x = Dense(
                        units=layer.units, 
                        activation=layer.activation,
                        activity_regularizer=reg,
                        name="layer_%d"%n_layer)(x)
                elif n_layer%2 != 0:
                    x_input = x
                    x = Dense(
                        units=layer.units, 
                        activation=layer.activation, 
                        activity_regularizer=reg,
                        name="layer_%d"%n_layer)(x)
                else:
                    x = Add(name="add_%d" % n_layer)([x, x_input])
                    x = Dense(
                        units=layer.units, 
                        activation=layer.activation, 
                        activity_regularizer=reg,
                        name="layer_%d"%n_layer)(x)
                    #x = Activation(layer['activation'],
                    #    name="activation_%d"%n_layer)(x)
            else:
                x = Dense(
                    units=layer.units, 
                    activation=layer.activation, 
                    activity_regularizer=reg,
                    name="layer_%d"%n_layer)(x)    
            # x = BatchNormalization()(x)
            # x = Dropout(float(layer.dropout_rate))(x)  

    outputs = []
    for layer in config.outputlayers:
        if layer.type == 'Dense':
            output = Dense(
                units=layer.units,
                kernel_initializer=layer.kernel_initializer, 
                activation=layer.activation, 
                activity_regularizer=reg, 
                name=layer.name)(x)
            outputs.append(output)
        
    return Model(inputs=input_layer, outputs=outputs, name=config.name)

In [98]:
import pandas as pd
import numpy as np
import random
from pathlib import Path
import yaml
import tf2onnx
import tensorflow as tf
from sklearn.inspection import permutation_importance
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Input, Masking, Normalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.utils import plot_model
from contextlib import redirect_stdout
import post_processing.References as Refs
import post_processing.NN.model_builder as model_builder
import  post_processing.NN.utils as utils
from post_processing.NN.utils import ModelConfig

class DNNModel:

    def __init__(self, model_config: ModelConfig, modeldir: Path = None):
        self.config = model_config
        self.name = model_config.name
        self.type = model_config.type
        self.categorization = model_config.categorization
        self.training_weight_sf = model_config.training_weight_sf
        self.input_vars = model_config.input_vars
        self.classes = [class_i for class_i in model_config.categorization.keys() if class_i]
        self.processes = [proc for proc_list in model_config.categorization.values() for proc in proc_list]
        self.model_df = None
        self.model = None
        self.history = None
        self.modeldir = modeldir
        if modeldir is not None:
            self.modeldir.mkdir(parents=True, exist_ok=True)

        if self.type == 'binary': self._validate_categorization_for_binary()
            
        print(f"Initializing model: {self.name}")

    def _validate_categorization_for_binary(self):
        if len(self.categorization) !=2 : 
            raise ValueError("Dictionary for binary classifier must contain exactly two items")
        has_empty_key = "" in self.categorization
        has_non_empty_key = any(k for k in self.categorization.keys() )
        if not (has_empty_key and has_non_empty_key):
            raise ValueError("Dictionary must be of the form {'isSignal': ['HH'], "": ['ttbar', 'tW']}")
        self.categorization = {k: v for k, v in self.categorization.items() if k}
        print(f"self.categorization: {self.categorization}")

    def set_model_df_from_total_df(self, total_df: pd.DataFrame = None):
        '''
        This function does the following: 
            - Picks only the features (or input variables) noted in 'input_vars'
            - Keeps only the events corresponding to all training processes
            - Adds a training weight to each event normalized by the process it corresponds to
        '''

        for proc in self.processes:
            assert f"Process_{proc}" in total_df.columns, f"Process {proc} was not found in the total dataframe"

        model_df = total_df.copy()

        if self.input_vars != 'All':
            # To do: Resolve if input_vars not found  in df
            columns_to_keep = ['event', 'genWeight']
            columns_to_keep.extend(col for col in model_df.columns if col.startswith('Process_'))
            model_df = model_df[self.input_vars + columns_to_keep]
            
        # Keep only events corresponding to any of the training processes indicated ------
        condition = False
        for process in self.processes:
            condition |= (model_df[f'Process_{process}'] == 1)
        model_df = model_df[condition]

        # Adding training weights (normalized per process) -------------------------------
        model_df["sample_weight"] = model_df['genWeight'].copy()
        hh_total_weight = 0

        # Apply training weights ---------------------------------------------------------
        if 'HH' in self.processes:
            hh_mask = (model_df["Process_HH"] == 1)
            hh_total_weight = model_df[hh_mask]["genWeight"].sum()

        for process in self.processes:
            process_mask = (model_df[f"Process_{process}"] == 1)
            process_total_sum = model_df[process_mask]["genWeight"].sum()
            scaling_factor = 1
            if process in self.training_weight_sf:
                scaling_factor = self.training_weight_sf[process]
            model_df.loc[process_mask, "sample_weight"] *= (scaling_factor * (model_df.shape[0] / process_total_sum))

        # Create classes as specified in categorization ----------------------------------
        for class_i, class_i_processes in self.categorization.items():
            model_df[f"Class_{class_i}"] = 0
            for proc in class_i_processes:
                model_df.loc[model_df[f"Process_{proc}"] == 1, f"Class_{class_i}"] = 1

        # Printing only ------------------------------------------------------------------
        for process in self.processes:
            column_name = f"Process_{process}"
            print(column_name)
            process_mask = model_df[column_name] == 1
            process_total_genWeight = model_df[process_mask]['genWeight'].sum()
            process_total_sample_weight = model_df[process_mask]['sample_weight'].sum()
            print(f"Total sum of genWeights for {process}: {process_total_genWeight} ")
            print(f"Total sum of sample_weights for {process}: {process_total_sample_weight} ")

        # Drop 'Process_' columns
        columns_to_drop = [col for col in model_df.columns if col.startswith('Process_')]
        others_to_drop = ['File']
        model_df = model_df.drop(columns=columns_to_drop+others_to_drop)

        self.model_df = model_df

        print(f"\tModel dataframe:\n{model_df}")

        return model_df
    
    @staticmethod
    def get_X_and_Y_from_model_df(model_df):
        classes = [cls_i for cls_i in model_df.columns if cls_i.startswith('Class_')]
        also_drop_from_X = ["event", "genWeight", "sample_weight"]
        X_df = model_df.drop(columns=classes + also_drop_from_X)
        Y_df = model_df[classes]
        events = model_df["event"]
        sample_weights = model_df["sample_weight"]

        return X_df, Y_df, events, sample_weights

    @staticmethod
    def get_train_and_test_split(X_df: pd.DataFrame, Y_df: pd.DataFrame, events: pd.Series, sample_weights: pd.Series, split_type='train_test_split', train_index=None, test_index=None):

        if split_type == 'train_test_split':
            test_size = 0.2
            X_train, X_test, Y_train, Y_test, evs_train, evs_test, sw_train, sw_test = train_test_split(X_df, Y_df, events, sample_weights, test_size=test_size, random_state=7, stratify=Y_df.idxmax(axis=1))
        elif split_type == 'skf':
            assert all(idx is not None for idx in [train_index, test_index])
            X_train, X_test = X_df.iloc[train_index], X_df.iloc[test_index]
            Y_train, Y_test = Y_df.iloc[train_index], Y_df.iloc[test_index]
            evs_train, evs_test = events.iloc[train_index], events.iloc[test_index]
            sw_train, sw_test = sample_weights.iloc[train_index], sample_weights.iloc[test_index]

        return X_train, X_test, Y_train, Y_test, evs_test, sw_train

    def input_preprocessing(self, X_train):
        print(f"\tPreprocessing input ...")
        print(f"\tmask value isss {self.mask_value}")

        ndim = len(X_train.columns)
        input_layer = Input(shape=(ndim, ), name="input")
        masked_inputs = Masking(mask_value=self.mask_value)(input_layer)
        X_train_valid = X_train.replace(self.mask_value, np.nan)

        print(f"Mean: {X_train_valid.mean(axis=0)}")
        print(f"Variance: {X_train_valid.var(axis=0)}")

        normalizer = Normalization(
                        mean=X_train_valid.mean(axis=0).to_numpy(),
                        variance=X_train_valid.var(axis=0).to_numpy(),
                        name='normalization')
        normalized_input = normalizer(masked_inputs)        

        return input_layer, normalized_input

    def build_model(self, input_layer, normalized_input, fixed_random_seed: bool = True):
        print(f'\tBuilding model ...')

        if fixed_random_seed:
            # Set seeds for reproducibility
            seed_value = 42
            tf.random.set_seed(seed_value)
            np.random.seed(seed_value)
            random.seed(seed_value)

        if self.config.architecture_in_yml:
            # model = model_builder.setup_architecture_from_yml(self.config, input_layer, normalized_input)
            model = setup_architecture_from_yml(self.config, input_layer, normalized_input)
        else:
            arch_fnc_name = self.config.architecture_name
            nodes_per_layer = self.config.nodes_per_layer
            model = model_builder.setup_architecture_from_fnc(arch_fnc_name, nodes_per_layer, input_layer, normalized_input, len(self.classes))

        loss = model_builder.get_loss(self.config.compiler.loss)

        model.compile(
            optimizer=model_builder.get_optimizer(self.config.compiler),
            loss=loss,
            metrics = model_builder.get_metrics(self.classes),
            weighted_metrics = []
        )

        print(f"Sumary of model compiled")
        model.summary()

        self.model = model

        return model

    def train_model(self, X_train, Y_train, sw_train):
        print(f"\tTraining model ...")

        Y_train = Y_train.astype('float32')
        sw_train = sw_train.astype('float32')

        early_stopping = EarlyStopping(monitor='val_loss', min_delta=0.001, patience=20, verbose=0, mode='min', restore_best_weights=True)
        reduce_plateau = ReduceLROnPlateau(monitor='val_loss', factor=0.1, min_delta=0.001, patience=10, min_lr=1e-8, verbose=0, mode='min')
        terminate_on_nan = tf.keras.callbacks.TerminateOnNaN()

        history = self.model.fit(
            X_train, 
            Y_train, 
            batch_size=self.config.fit.batch_size, 
            epochs=self.config.fit.epochs, 
            sample_weight=sw_train,
            validation_split=self.config.fit.validation_split,  
            callbacks=[early_stopping, reduce_plateau, terminate_on_nan])

        self.history = history

        return self.history
    
    def save_model_info(self, features, Y_train, Y_test):
        print(f"\tSaving model info ...")
        model_onnx, external_tensor_storage = tf2onnx.convert.from_keras(self.model, output_path=self.modeldir/'dnn_model.onnx')

        plot_model(self.model, to_file=self.modeldir/'model_plot.png', show_shapes=True, show_layer_names=True)
    
        with open(self.modeldir / 'model_summary.txt', 'w') as f:
            with redirect_stdout(f):
               self.model.summary()

        input_names = features.tolist()
        input_vars_file = self.modeldir /'input_variables.txt'
        with open(input_vars_file, 'w') as file:
            for name in input_names:
                file.write(name + '\n')

        self.config.training_events['Total'] = len(Y_train)
        self.config.testing_events['Total'] = len(Y_test)
        for cls_i in self.classes:
            self.config.training_events[cls_i] = int(Y_train['Class_'+cls_i].value_counts()[1])
            self.config.testing_events[cls_i] = int(Y_test['Class_'+cls_i].value_counts()[1])

        out_yml = self.modeldir / 'model_info.yml'
        with open(out_yml, 'w') as file:
            yaml.dump(self.config.__getstate__(), file, sort_keys=False)

    def evaluate_and_predict(self, X_test, Y_test, events_test) -> tuple[pd.DataFrame, dict]:
        print(f"\tEvaluating model and predicting ...")
        Y_test = Y_test.astype('float32') 
        model_metrics = self.model.evaluate(X_test, Y_test, verbose=0, return_dict=True)   
        if np.isnan(model_metrics['loss']):
            raise ValueError(f"Nan detected in evaluation for model {self.name}")
        print(model_metrics)
        events_test.reset_index(drop=True, inplace=True)
        Y_test.reset_index(drop=True, inplace=True)
        output_df = pd.concat([events_test, Y_test], axis=1)
        Y_pred_score = self.model.predict(X_test)
        for i, cls in enumerate(Y_test.columns):
            column_name = 'Score_' + cls.removeprefix('Class_')
            score = Y_pred_score[:, i]
            cls_score = pd.Series(score.flatten(), name=column_name).reset_index(drop=True)
            output_df = pd.concat([output_df, cls_score], axis=1)
        print(f"\tPredictions:\n{output_df.head()}")
        output_df.to_csv(self.modeldir / 'predictions.csv', index=False)
        return output_df, model_metrics
   
    def feature_ranking(self, X_test, Y_test):
        print(f"\tFeature Ranking ...")

        class KerasRegressorWrapper(BaseEstimator, RegressorMixin):
            def __init__(self, model):
                self.model = model

            def fit(self, X, y):
                self.model.fit(X, y)
                return self

            def predict(self, X):
                return self.model.predict(X)
            
        estimator = KerasRegressorWrapper(self.model)
        result = permutation_importance(estimator, X_test, Y_test, n_repeats=10, random_state=42)
        sorted_idx = result.importances_mean.argsort()
        features_list = X_test.columns.tolist()
        features_ranked = [features_list[idx] for idx in sorted_idx]

        features_ranking_file = self.modeldir / "features_ranking.txt"
        with open(features_ranking_file, 'w') as file:
            file.write(f"Number of features: {len(features_list)}\n")
            file.write(f"Ranking: \n")
            for i, ranked_f in enumerate(features_ranked):
                file.write(f"{i+1}. {ranked_f}\n")

    @staticmethod
    def Full_Splitting(model_df: pd.DataFrame=None):
        assert model_df is not None
        X_df, Y_df, events, sample_weights = DNNModel.get_X_and_Y_from_model_df(model_df)        
        X_train, X_test, Y_train, Y_test, evs_test, sw_train = DNNModel.get_train_and_test_split(X_df=X_df, Y_df=Y_df, events=events, sample_weights=sample_weights, split_type='train_test_split')
        return X_train, X_test, Y_train, Y_test, evs_test, sw_train

    def Train(self, X_train, Y_train, sw_train, Y_test, fixed_random_seed: bool = True):
        input_layer, normalized_input = self.input_preprocessing(X_train)
        self.build_model(input_layer=input_layer, normalized_input=normalized_input, fixed_random_seed=fixed_random_seed)
        self.train_model(X_train, Y_train, sw_train)
        self.save_model_info(X_train.columns, Y_train, Y_test)

    def Evaluate(self, X_test, Y_test, evs_test, rank_features=False):
        output_df, model_metrics = self.evaluate_and_predict(X_test, Y_test, evs_test)
        cm_norm_true, cm_norm_pred, diag_names = utils.draw_all_stats(DNN_type=self.type, history=self.history, output_df=output_df, modeldir=self.modeldir, classes=self.classes)
        if rank_features: self.feature_ranking(X_test, Y_test)
        return model_metrics, cm_norm_true, cm_norm_pred, diag_names

    def Run(self, total_df, fixed_random_seed, rank_features=False):
        model_df = self.set_model_df_from_total_df(total_df)
        X_train, X_test, Y_train, Y_test, evs_test, sw_train = self.Full_Splitting(model_df)
        self.Train(X_train, Y_train, sw_train, Y_test, fixed_random_seed)
        # model_metrics, cm_norm_true, cm_norm_pred, diag_names = self.Evaluate(X_test, Y_test, evs_test, rank_features)
        # return model_metrics, cm_norm_true, cm_norm_pred, diag_names
        return

# Set up your model config

In [99]:
from post_processing.NN.utils import ModelConfig
model_config = ModelConfig(
    name='multi_HH_ttbar_tW',
    type='multi',
    categorization={"HH": ["HH_bbWW"], "ttbar": ["ttbar"], "tW": ["tW"]},
    training_weight_sf={"HH_bbWW": 1.0, "ttbar": 8.0, "tW": 4.0},
    input_vars='All',
    architecture_in_yml=True,
    residual_network=False,
    hiddenlayers=[
        {"type": 'Dense', "units": 16, "activation": 'relu', "act_regularizer": {'l2': 1e-4}, "dropout_rate": 0.4}
        # {"type": 'Dense', "units": 16, "activation": 'relu', "act_regularizer": {'l2': 1e-4}, "dropout_rate": 0.4},
        # {"type": 'Dense', "units": 16, "activation": 'relu', "act_regularizer": {'l2': 1e-4}, "dropout_rate": 0.4}
    ],
    outputlayers=[
        {"type": 'Dense', "units": 3, "kernel_initializer": 'normal', "activation": 'softmax', "act_regularizer": {'l2': 1e-4}, "name": 'output'}
    ],
    compiler={"optimizer": 'adam', "lr": 0.001, "loss": 'categorical_crossentropy'},
    fit={"batch_size": 1024, "epochs": 2, "validation_split": 0.25}
)

# Run DNN

### Version 0: np.nan

In [100]:
preprocessed_df_v4.tail()

           event     genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr      File  Process_DY  Process_HH_bbWW  Process_HH_bbtautau  Process_VV  Process_WJets  Process_tW  Process_ttbar
29962  744617994  83745.546875        -0.275          -1.727          -1.356        -1.671          0.849   -0.132            0.368             -0.112  Wjets_2J           0                0                    0           0              1           0              0
30323  744899478  83745.546875        -0.288           0.327          -0.377        -0.090         -0.269   -0.151           -0.445             -0.622  Wjets_2J           0                0                    0           0              1           0              0
30340  745108688  83745.546875        -0.223           0.343           0.757         1.520          0.263    0.193            0.558             -0.775  Wjets_2J           0                0                    0           0              1           0              0
30318  745244862  83745.546875        -0.219             NaN           0.886        -1.550        -20.000   -0.071           -1.004              0.563  Wjets_2J           0                0                    0           0              1           0              0
30007  745344992  83745.546875        -0.233           0.312           0.284        -1.004         -1.397    0.002           -0.136             -0.571  Wjets_2J           0                0                    0           0              1           0              0

In [104]:
DNN = DNNModel(model_config=model_config, modeldir= NOTEBOOKSDIR/'model_npnan')
DNN.mask_value = np.nan
DNN.Run(preprocessed_df_v4, fixed_random_seed=True)

Initializing model: multi_HH_ttbar_tW
Process_HH_bbWW
Total sum of genWeights for HH_bbWW: 108.30008697509766
Total sum of sample_weights for HH_bbWW: 1857345.9098510742
Process_ttbar
Total sum of genWeights for ttbar: 381467648.0
Total sum of sample_weights for ttbar: 14858771.06210621
Process_tW
Total sum of genWeights for tW: 8042688.5
Total sum of sample_weights for tW: 7429384.208231437
	Model dataframe:
            event   genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr  sample_weight  Class_HH  Class_ttbar  Class_tW
186577         18    3.805950        -0.278           0.401           0.742         1.496          1.167    0.428            0.439              0.014       3.515723         0            0         1
13167          32    0.033119        -0.242           0.329           0.937         1.507          0.849    0.393            0.549              1.259     567.997559         1            0         0
706510         36   81.103897        -0.322          -0.791          -1.330        -2.183         -2.512   -0.028            0.317             -0.649       3.159125         0            1         0
13168          42    0.033119         0.132           0.239           1.084         1.504          0.714    0.130            0.117             -0.098     567.997559         1            0         0
11905          58    0.033119         0.109           0.358           0.747         1.493          1.051   -0.491            0.396             -0.674     567.997559         1            0         0
...           ...         ...           ...             ...             ...           ...            ...      ...              ...                ...            ...       ...          ...       ...
1383502  79999662  337.046997        -0.233           0.350           0.384         1.533         -0.991    0.068            0.271              0.563      13.128513         0            1         0
1307638  79999672  337.046997         0.245           0.164          -0.629        -0.645          1.120   -0.184            0.389             -0.204      13.128513         0            1         0
906730   79999852  337.046997        -0.260           0.304          -1.322        -1.059         -0.895   -0.244           -0.445             -0.733      13.128513         0            1         0
1241332  79999874  337.046997         0.015             NaN          -1.392        -3.735         -4.007   -0.444            0.435             -0.073      13.128513         0            1         0
1583489  79999908  337.046997        -0.263           0.344          -1.614        -1.566          1.186    0.403           -0.394             -0.151      13.128513         0            1         0

[1857346 rows x 14 columns]
	Preprocessing input ...
	mask value isss nan
Mean: bjet0_pt_llr        -0.105481
bjets_dEta_llr      -0.407105
bjets_dPhi_llr      -0.534035
bjets_dR_llr        -0.712892
bjets_mbb_llr       -2.883128
mjj_llr             -0.065720
trijet_mInv_llr     -0.058991
trijet_pt_rat_llr   -0.365355
dtype: float64
Variance: bjet0_pt_llr          1.187154
bjets_dEta_llr        4.008633
bjets_dPhi_llr        3.319234
bjets_dR_llr          2.244745
bjets_mbb_llr        38.473088
mjj_llr               0.106370
trijet_mInv_llr       0.359366
trijet_pt_rat_llr     3.633118
dtype: float64
	Building model ...
		Setting up architecture from yml ...
		Testing without BN ...
		With RN now ...
		Getting loss categorical_crossentropy...
Sumary of model compiled
Model: "multi_HH_ttbar_tW"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input (InputLayer)          [(None, 8)]               0

 masking_31 (Masking)        (None, 8)                 0

 normalization (Normalizati  (None, 8)                 0
 on)

 layer_0 (Dense)             (None, 16)                144

 output (Dense)              (None, 3)                 51

=================================================================
Total params: 195 (780.00 Byte)
Trainable params: 195 (780.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
	Training model ...
Epoch 1/2
1089/1089 [==============================] - 5s 3ms/step - loss: 12.2716 - accuracy: 0.8537 - precision: 0.8546 - recall: 0.4141 - auc_roc: 0.9193 - auc_pr: 0.8170 - f1_score_macro: 0.3075 - f1_score_micro: 0.8537 - precision_HH: 0.0000e+00 - recall_HH: 0.0000e+00 - precision_ttbar: 0.8546 - recall_ttbar: 0.4846 - precision_tW: 0.3333 - recall_tW: 6.2369e-06 - val_loss: 11.3612 - val_accuracy: 0.8541 - val_precision: 0.8541 - val_recall: 0.8541 - val_auc_roc: 0.9262 - val_auc_pr: 0.8219 - val_f1_score_macro: 0.3071 - val_f1_score_micro: 0.8541 - val_precision_HH: 0.0000e+00 - val_recall_HH: 0.0000e+00 - val_precision_ttbar: 0.8541 - val_recall_ttbar: 1.0000 - val_precision_tW: 0.0000e+00 - val_recall_tW: 0.0000e+00 - lr: 0.0010
Epoch 2/2
1089/1089 [==============================] - 2s 2ms/step - loss: 11.2347 - accuracy: 0.8544 - precision: 0.8544 - recall: 0.8544 - auc_roc: 0.9263 - auc_pr: 0.8226 - f1_score_macro: 0.3072 - f1_score_micro: 0.8544 - precision_HH: 0.0000e+00 - recall_HH: 0.0000e+00 - precision_ttbar: 0.8544 - recall_ttbar: 1.0000 - precision_tW: 0.0000e+00 - recall_tW: 0.0000e+00 - val_loss: 11.1580 - val_accuracy: 0.8541 - val_precision: 0.8541 - val_recall: 0.8541 - val_auc_roc: 0.9262 - val_auc_pr: 0.8219 - val_f1_score_macro: 0.3071 - val_f1_score_micro: 0.8541 - val_precision_HH: 0.0000e+00 - val_recall_HH: 0.0000e+00 - val_precision_ttbar: 0.8541 - val_recall_ttbar: 1.0000 - val_precision_tW: 0.0000e+00 - val_recall_tW: 0.0000e+00 - lr: 0.0010

Could not search for non-variable resources. Concrete function internal representation may have changed.

	Saving model info ...

2024-10-19 02:08:26.131298: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 02:08:26.131462: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2024-10-19 02:08:26.206240: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 02:08:26.206372: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session

### Version 1: -9999

In [47]:
preprocessed_df.tail()

           event     genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr      File  Process_DY  Process_HH_bbWW  Process_HH_bbtautau  Process_VV  Process_WJets  Process_tW  Process_ttbar
29962  744617994  83745.546875        -0.275          -1.727          -1.356        -1.671          0.849   -0.132            0.368             -0.112  Wjets_2J           0                0                    0           0              1           0              0
30323  744899478  83745.546875        -0.288           0.327          -0.377        -0.090         -0.269   -0.151           -0.445             -0.622  Wjets_2J           0                0                    0           0              1           0              0
30340  745108688  83745.546875        -0.223           0.343           0.757         1.520          0.263    0.193            0.558             -0.775  Wjets_2J           0                0                    0           0              1           0              0
30318  745244862  83745.546875        -0.219       -9999.000           0.886        -1.550        -20.000   -0.071           -1.004              0.563  Wjets_2J           0                0                    0           0              1           0              0
30007  745344992  83745.546875        -0.233           0.312           0.284        -1.004         -1.397    0.002           -0.136             -0.571  Wjets_2J           0                0                    0           0              1           0              0

In [88]:
DNN = DNNModel(model_config=model_config, modeldir= NOTEBOOKSDIR/'model_m9999')
DNN.mask_value = -9999
DNN.Run(preprocessed_df, fixed_random_seed=True)

Initializing model: multi_HH_ttbar_tW

Process_HH_bbWW
Total sum of genWeights for HH_bbWW: 108.30008697509766
Total sum of sample_weights for HH_bbWW: 1857345.9098510742
Process_ttbar
Total sum of genWeights for ttbar: 381467648.0
Total sum of sample_weights for ttbar: 14858771.06210621
Process_tW
Total sum of genWeights for tW: 8042688.5
Total sum of sample_weights for tW: 7429384.208231437
	Model dataframe:
            event   genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr  sample_weight  Class_HH  Class_ttbar  Class_tW
186577         18    3.805950        -0.278           0.401           0.742         1.496          1.167    0.428            0.439              0.014       3.515723         0            0         1
13167          32    0.033119        -0.242           0.329           0.937         1.507          0.849    0.393            0.549              1.259     567.997559         1            0         0
706510         36   81.103897        -0.322          -0.791          -1.330        -2.183         -2.512   -0.028            0.317             -0.649       3.159125         0            1         0
13168          42    0.033119         0.132           0.239           1.084         1.504          0.714    0.130            0.117             -0.098     567.997559         1            0         0
11905          58    0.033119         0.109           0.358           0.747         1.493          1.051   -0.491            0.396             -0.674     567.997559         1            0         0
...           ...         ...           ...             ...             ...           ...            ...      ...              ...                ...            ...       ...          ...       ...
1383502  79999662  337.046997        -0.233           0.350           0.384         1.533         -0.991    0.068            0.271              0.563      13.128513         0            1         0
1307638  79999672  337.046997         0.245           0.164          -0.629        -0.645          1.120   -0.184            0.389             -0.204      13.128513         0            1         0
906730   79999852  337.046997        -0.260           0.304          -1.322        -1.059         -0.895   -0.244           -0.445             -0.733      13.128513         0            1         0
1241332  79999874  337.046997         0.015       -9999.000          -1.392        -3.735         -4.007   -0.444            0.435             -0.073      13.128513         0            1         0
1583489  79999908  337.046997        -0.263           0.344          -1.614        -1.566          1.186    0.403           -0.394             -0.151      13.128513         0            1         0

[1857346 rows x 14 columns]
	Preprocessing input ...
	mask value isss -9999
Mean: bjet0_pt_llr        -0.105481
bjets_dEta_llr      -0.407105
bjets_dPhi_llr      -0.534035
bjets_dR_llr        -0.712892
bjets_mbb_llr       -2.883128
mjj_llr             -0.065720
trijet_mInv_llr     -0.058991
trijet_pt_rat_llr   -0.365355
dtype: float64
Variance: bjet0_pt_llr          1.187154
bjets_dEta_llr        4.008633
bjets_dPhi_llr        3.319234
bjets_dR_llr          2.244745
bjets_mbb_llr        38.473088
mjj_llr               0.106370
trijet_mInv_llr       0.359366
trijet_pt_rat_llr     3.633118
dtype: float64
	Building model ...
		Setting up architecture from yml ...
		Testing without BN ...
		With RN now ...
		Getting loss categorical_crossentropy...
Sumary of model compiled
Model: "multi_HH_ttbar_tW"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input (InputLayer)          [(None, 8)]               0

 masking_23 (Masking)        (None, 8)                 0

 normalization (Normalizati  (None, 8)                 0
 on)

 layer_0 (Dense)             (None, 16)                144

 output (Dense)              (None, 3)                 51

=================================================================
Total params: 195 (780.00 Byte)
Trainable params: 195 (780.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
	Training model ...
Epoch 1/2
1089/1089 [==============================] - 5s 3ms/step - loss: 15.3758 - accuracy: 0.8335 - precision: 0.8521 - recall: 0.6732 - auc_roc: 0.9179 - auc_pr: 0.8055 - f1_score_macro: 0.3270 - f1_score_micro: 0.8335 - precision_HH: 0.0052 - recall_HH: 5.0916e-04 - precision_ttbar: 0.8606 - recall_ttbar: 0.7844 - precision_tW: 0.2727 - recall_tW: 0.0210 - val_loss: 12.2885 - val_accuracy: 0.8440 - val_precision: 0.8501 - val_recall: 0.8201 - val_auc_roc: 0.9186 - val_auc_pr: 0.7991 - val_f1_score_macro: 0.3302 - val_f1_score_micro: 0.8440 - val_precision_HH: 0.0000e+00 - val_recall_HH: 0.0000e+00 - val_precision_ttbar: 0.8622 - val_recall_ttbar: 0.9542 - val_precision_tW: 0.2635 - val_recall_tW: 0.0353 - lr: 0.0010
Epoch 2/2
1089/1089 [==============================] - 3s 2ms/step - loss: 12.2438 - accuracy: 0.8457 - precision: 0.8534 - recall: 0.8120 - auc_roc: 0.9278 - auc_pr: 0.8201 - f1_score_macro: 0.3304 - f1_score_micro: 0.8457 - precision_HH: 0.0000e+00 - recall_HH: 0.0000e+00 - precision_ttbar: 0.8626 - recall_ttbar: 0.9458 - precision_tW: 0.2746 - recall_tW: 0.0275 - val_loss: 11.3094 - val_accuracy: 0.8511 - val_precision: 0.8581 - val_recall: 0.8053 - val_auc_roc: 0.9327 - val_auc_pr: 0.8377 - val_f1_score_macro: 0.3203 - val_f1_score_micro: 0.8511 - val_precision_HH: 0.0000e+00 - val_recall_HH: 0.0000e+00 - val_precision_ttbar: 0.8602 - val_recall_ttbar: 0.9414 - val_precision_tW: 0.3284 - val_recall_tW: 0.0084 - lr: 0.0010

Could not search for non-variable resources. Concrete function internal representation may have changed.

	Saving model info ...

2024-10-19 01:54:26.844985: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 01:54:26.845508: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2024-10-19 01:54:26.924844: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 01:54:26.925136: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session

In [89]:
DNN = DNNModel(model_config=model_config, modeldir= NOTEBOOKSDIR/'model_m9999_2')
DNN.mask_value = -9999
DNN.Run(preprocessed_df, fixed_random_seed=True)

Initializing model: multi_HH_ttbar_tW
Process_HH_bbWW
Total sum of genWeights for HH_bbWW: 108.30008697509766
Total sum of sample_weights for HH_bbWW: 1857345.9098510742
Process_ttbar
Total sum of genWeights for ttbar: 381467648.0
Total sum of sample_weights for ttbar: 14858771.06210621
Process_tW
Total sum of genWeights for tW: 8042688.5
Total sum of sample_weights for tW: 7429384.208231437
	Model dataframe:
            event   genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr  sample_weight  Class_HH  Class_ttbar  Class_tW
186577         18    3.805950        -0.278           0.401           0.742         1.496          1.167    0.428            0.439              0.014       3.515723         0            0         1
13167          32    0.033119        -0.242           0.329           0.937         1.507          0.849    0.393            0.549              1.259     567.997559         1            0         0
706510         36   81.103897        -0.322          -0.791          -1.330        -2.183         -2.512   -0.028            0.317             -0.649       3.159125         0            1         0
13168          42    0.033119         0.132           0.239           1.084         1.504          0.714    0.130            0.117             -0.098     567.997559         1            0         0
11905          58    0.033119         0.109           0.358           0.747         1.493          1.051   -0.491            0.396             -0.674     567.997559         1            0         0
...           ...         ...           ...             ...             ...           ...            ...      ...              ...                ...            ...       ...          ...       ...
1383502  79999662  337.046997        -0.233           0.350           0.384         1.533         -0.991    0.068            0.271              0.563      13.128513         0            1         0
1307638  79999672  337.046997         0.245           0.164          -0.629        -0.645          1.120   -0.184            0.389             -0.204      13.128513         0            1         0
906730   79999852  337.046997        -0.260           0.304          -1.322        -1.059         -0.895   -0.244           -0.445             -0.733      13.128513         0            1         0
1241332  79999874  337.046997         0.015       -9999.000          -1.392        -3.735         -4.007   -0.444            0.435             -0.073      13.128513         0            1         0
1583489  79999908  337.046997        -0.263           0.344          -1.614        -1.566          1.186    0.403           -0.394             -0.151      13.128513         0            1         0

[1857346 rows x 14 columns]
	Preprocessing input ...
	mask value isss -9999
Mean: bjet0_pt_llr        -0.105481
bjets_dEta_llr      -0.407105
bjets_dPhi_llr      -0.534035
bjets_dR_llr        -0.712892
bjets_mbb_llr       -2.883128
mjj_llr             -0.065720
trijet_mInv_llr     -0.058991
trijet_pt_rat_llr   -0.365355
dtype: float64
Variance: bjet0_pt_llr          1.187154
bjets_dEta_llr        4.008633
bjets_dPhi_llr        3.319234
bjets_dR_llr          2.244745
bjets_mbb_llr        38.473088
mjj_llr               0.106370
trijet_mInv_llr       0.359366
trijet_pt_rat_llr     3.633118
dtype: float64
	Building model ...
		Setting up architecture from yml ...
		Testing without BN ...
		With RN now ...
		Getting loss categorical_crossentropy...
Sumary of model compiled
Model: "multi_HH_ttbar_tW"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input (InputLayer)          [(None, 8)]               0

 masking_24 (Masking)        (None, 8)                 0

 normalization (Normalizati  (None, 8)                 0
 on)

 layer_0 (Dense)             (None, 16)                144

 output (Dense)              (None, 3)                 51

=================================================================
Total params: 195 (780.00 Byte)
Trainable params: 195 (780.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
	Training model ...
Epoch 1/2
1089/1089 [==============================] - 6s 3ms/step - loss: 15.3758 - accuracy: 0.8335 - precision: 0.8521 - recall: 0.6732 - auc_roc: 0.9179 - auc_pr: 0.8055 - f1_score_macro: 0.3270 - f1_score_micro: 0.8335 - precision_HH: 0.0052 - recall_HH: 5.0916e-04 - precision_ttbar: 0.8606 - recall_ttbar: 0.7844 - precision_tW: 0.2727 - recall_tW: 0.0210 - val_loss: 12.2885 - val_accuracy: 0.8440 - val_precision: 0.8501 - val_recall: 0.8201 - val_auc_roc: 0.9186 - val_auc_pr: 0.7991 - val_f1_score_macro: 0.3302 - val_f1_score_micro: 0.8440 - val_precision_HH: 0.0000e+00 - val_recall_HH: 0.0000e+00 - val_precision_ttbar: 0.8622 - val_recall_ttbar: 0.9542 - val_precision_tW: 0.2635 - val_recall_tW: 0.0353 - lr: 0.0010
Epoch 2/2
1089/1089 [==============================] - 2s 2ms/step - loss: 12.2438 - accuracy: 0.8457 - precision: 0.8534 - recall: 0.8120 - auc_roc: 0.9278 - auc_pr: 0.8201 - f1_score_macro: 0.3304 - f1_score_micro: 0.8457 - precision_HH: 0.0000e+00 - recall_HH: 0.0000e+00 - precision_ttbar: 0.8626 - recall_ttbar: 0.9458 - precision_tW: 0.2746 - recall_tW: 0.0275 - val_loss: 11.3094 - val_accuracy: 0.8511 - val_precision: 0.8581 - val_recall: 0.8053 - val_auc_roc: 0.9327 - val_auc_pr: 0.8377 - val_f1_score_macro: 0.3203 - val_f1_score_micro: 0.8511 - val_precision_HH: 0.0000e+00 - val_recall_HH: 0.0000e+00 - val_precision_ttbar: 0.8602 - val_recall_ttbar: 0.9414 - val_precision_tW: 0.3284 - val_recall_tW: 0.0084 - lr: 0.0010

Could not search for non-variable resources. Concrete function internal representation may have changed.

	Saving model info ...

2024-10-19 01:55:15.218004: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 01:55:15.218150: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2024-10-19 01:55:15.293538: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 01:55:15.293850: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session

### Version 2: -9

In [62]:
preprocessed_df_v2.tail()

           event     genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr      File  Process_DY  Process_HH_bbWW  Process_HH_bbtautau  Process_VV  Process_WJets  Process_tW  Process_ttbar
29962  744617994  83745.546875        -0.275          -1.727          -1.356        -1.671          0.849   -0.132            0.368             -0.112  Wjets_2J           0                0                    0           0              1           0              0
30323  744899478  83745.546875        -0.288           0.327          -0.377        -0.090         -0.269   -0.151           -0.445             -0.622  Wjets_2J           0                0                    0           0              1           0              0
30340  745108688  83745.546875        -0.223           0.343           0.757         1.520          0.263    0.193            0.558             -0.775  Wjets_2J           0                0                    0           0              1           0              0
30318  745244862  83745.546875        -0.219          -9.000           0.886        -1.550        -20.000   -0.071           -1.004              0.563  Wjets_2J           0                0                    0           0              1           0              0
30007  745344992  83745.546875        -0.233           0.312           0.284        -1.004         -1.397    0.002           -0.136             -0.571  Wjets_2J           0                0                    0           0              1           0              0

In [91]:
DNN = DNNModel(model_config=model_config, modeldir= NOTEBOOKSDIR/'model_m9')
DNN.mask_value = -9
DNN.Run(preprocessed_df_v2, fixed_random_seed=True)

Initializing model: multi_HH_ttbar_tW
Process_HH_bbWW
Total sum of genWeights for HH_bbWW: 108.30008697509766
Total sum of sample_weights for HH_bbWW: 1857345.9098510742
Process_ttbar
Total sum of genWeights for ttbar: 381467648.0
Total sum of sample_weights for ttbar: 14858771.06210621
Process_tW
Total sum of genWeights for tW: 8042688.5
Total sum of sample_weights for tW: 7429384.208231437
	Model dataframe:
            event   genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr  sample_weight  Class_HH  Class_ttbar  Class_tW
186577         18    3.805950        -0.278           0.401           0.742         1.496          1.167    0.428            0.439              0.014       3.515723         0            0         1
13167          32    0.033119        -0.242           0.329           0.937         1.507          0.849    0.393            0.549              1.259     567.997559         1            0         0
706510         36   81.103897        -0.322          -0.791          -1.330        -2.183         -2.512   -0.028            0.317             -0.649       3.159125         0            1         0
13168          42    0.033119         0.132           0.239           1.084         1.504          0.714    0.130            0.117             -0.098     567.997559         1            0         0
11905          58    0.033119         0.109           0.358           0.747         1.493          1.051   -0.491            0.396             -0.674     567.997559         1            0         0
...           ...         ...           ...             ...             ...           ...            ...      ...              ...                ...            ...       ...          ...       ...
1383502  79999662  337.046997        -0.233           0.350           0.384         1.533         -0.991    0.068            0.271              0.563      13.128513         0            1         0
1307638  79999672  337.046997         0.245           0.164          -0.629        -0.645          1.120   -0.184            0.389             -0.204      13.128513         0            1         0
906730   79999852  337.046997        -0.260           0.304          -1.322        -1.059         -0.895   -0.244           -0.445             -0.733      13.128513         0            1         0
1241332  79999874  337.046997         0.015          -9.000          -1.392        -3.735         -4.007   -0.444            0.435             -0.073      13.128513         0            1         0
1583489  79999908  337.046997        -0.263           0.344          -1.614        -1.566          1.186    0.403           -0.394             -0.151      13.128513         0            1         0

[1857346 rows x 14 columns]
	Preprocessing input ...
	mask value isss -9
Mean: bjet0_pt_llr        -0.105481
bjets_dEta_llr      -0.407105
bjets_dPhi_llr      -0.534035
bjets_dR_llr        -0.712892
bjets_mbb_llr       -2.883128
mjj_llr             -0.065720
trijet_mInv_llr     -0.058991
trijet_pt_rat_llr   -0.365355
dtype: float64
Variance: bjet0_pt_llr          1.187154
bjets_dEta_llr        4.008633
bjets_dPhi_llr        3.319234
bjets_dR_llr          2.244745
bjets_mbb_llr        38.473088
mjj_llr               0.106370
trijet_mInv_llr       0.359366
trijet_pt_rat_llr     3.633118
dtype: float64
	Building model ...
		Setting up architecture from yml ...
		Testing without BN ...
		With RN now ...
		Getting loss categorical_crossentropy...
Sumary of model compiled
Model: "multi_HH_ttbar_tW"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input (InputLayer)          [(None, 8)]               0

 masking_26 (Masking)        (None, 8)                 0

 normalization (Normalizati  (None, 8)                 0
 on)

 layer_0 (Dense)             (None, 16)                144

 output (Dense)              (None, 3)                 51

=================================================================
Total params: 195 (780.00 Byte)
Trainable params: 195 (780.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
	Training model ...
Epoch 1/2
1089/1089 [==============================] - 5s 3ms/step - loss: 10.8316 - accuracy: 0.8367 - precision: 0.8487 - recall: 0.7162 - auc_roc: 0.9261 - auc_pr: 0.8307 - f1_score_macro: 0.3410 - f1_score_micro: 0.8367 - precision_HH: 0.0000e+00 - recall_HH: 0.0000e+00 - precision_ttbar: 0.8615 - recall_ttbar: 0.8294 - precision_tW: 0.3552 - recall_tW: 0.0529 - val_loss: 10.3550 - val_accuracy: 0.8461 - val_precision: 0.8481 - val_recall: 0.7608 - val_auc_roc: 0.9308 - val_auc_pr: 0.8406 - val_f1_score_macro: 0.3453 - val_f1_score_micro: 0.8461 - val_precision_HH: 0.0000e+00 - val_recall_HH: 0.0000e+00 - val_precision_ttbar: 0.8626 - val_recall_ttbar: 0.8802 - val_precision_tW: 0.3519 - val_recall_tW: 0.0622 - lr: 0.0010
Epoch 2/2
1089/1089 [==============================] - 2s 2ms/step - loss: 10.2854 - accuracy: 0.8392 - precision: 0.8450 - recall: 0.7616 - auc_roc: 0.9302 - auc_pr: 0.8384 - f1_score_macro: 0.3628 - f1_score_micro: 0.8392 - precision_HH: 0.0501 - recall_HH: 0.0092 - precision_ttbar: 0.8641 - recall_ttbar: 0.8787 - precision_tW: 0.3377 - recall_tW: 0.0755 - val_loss: 10.1833 - val_accuracy: 0.8349 - val_precision: 0.8427 - val_recall: 0.7594 - val_auc_roc: 0.9299 - val_auc_pr: 0.8380 - val_f1_score_macro: 0.3696 - val_f1_score_micro: 0.8349 - val_precision_HH: 0.0891 - val_recall_HH: 0.0339 - val_precision_ttbar: 0.8651 - val_recall_ttbar: 0.8744 - val_precision_tW: 0.3365 - val_recall_tW: 0.0867 - lr: 0.0010

Could not search for non-variable resources. Concrete function internal representation may have changed.

	Saving model info ...

2024-10-19 01:56:13.542013: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 01:56:13.542202: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2024-10-19 01:56:13.617401: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 01:56:13.617524: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session

### Version 3: +9999

In [ ]:
preprocessed_df_v3.tail()

In [93]:
DNN = DNNModel(model_config=model_config, modeldir= NOTEBOOKSDIR/'model_p9999')
DNN.mask_value = 9999
DNN.Run(preprocessed_df_v3, fixed_random_seed=True)

Initializing model: multi_HH_ttbar_tW
Process_HH_bbWW
Total sum of genWeights for HH_bbWW: 108.30008697509766
Total sum of sample_weights for HH_bbWW: 1857345.9098510742
Process_ttbar
Total sum of genWeights for ttbar: 381467648.0
Total sum of sample_weights for ttbar: 14858771.06210621
Process_tW
Total sum of genWeights for tW: 8042688.5
Total sum of sample_weights for tW: 7429384.208231437
	Model dataframe:
            event   genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr  sample_weight  Class_HH  Class_ttbar  Class_tW
186577         18    3.805950        -0.278           0.401           0.742         1.496          1.167    0.428            0.439              0.014       3.515723         0            0         1
13167          32    0.033119        -0.242           0.329           0.937         1.507          0.849    0.393            0.549              1.259     567.997559         1            0         0
706510         36   81.103897        -0.322          -0.791          -1.330        -2.183         -2.512   -0.028            0.317             -0.649       3.159125         0            1         0
13168          42    0.033119         0.132           0.239           1.084         1.504          0.714    0.130            0.117             -0.098     567.997559         1            0         0
11905          58    0.033119         0.109           0.358           0.747         1.493          1.051   -0.491            0.396             -0.674     567.997559         1            0         0
...           ...         ...           ...             ...             ...           ...            ...      ...              ...                ...            ...       ...          ...       ...
1383502  79999662  337.046997        -0.233           0.350           0.384         1.533         -0.991    0.068            0.271              0.563      13.128513         0            1         0
1307638  79999672  337.046997         0.245           0.164          -0.629        -0.645          1.120   -0.184            0.389             -0.204      13.128513         0            1         0
906730   79999852  337.046997        -0.260           0.304          -1.322        -1.059         -0.895   -0.244           -0.445             -0.733      13.128513         0            1         0
1241332  79999874  337.046997         0.015        9999.000          -1.392        -3.735         -4.007   -0.444            0.435             -0.073      13.128513         0            1         0
1583489  79999908  337.046997        -0.263           0.344          -1.614        -1.566          1.186    0.403           -0.394             -0.151      13.128513         0            1         0

[1857346 rows x 14 columns]
	Preprocessing input ...
	mask value isss 9999
Mean: bjet0_pt_llr        -0.105481
bjets_dEta_llr      -0.407105
bjets_dPhi_llr      -0.534035
bjets_dR_llr        -0.712892
bjets_mbb_llr       -2.883128
mjj_llr             -0.065720
trijet_mInv_llr     -0.058991
trijet_pt_rat_llr   -0.365355
dtype: float64
Variance: bjet0_pt_llr          1.187154
bjets_dEta_llr        4.008633
bjets_dPhi_llr        3.319234
bjets_dR_llr          2.244745
bjets_mbb_llr        38.473088
mjj_llr               0.106370
trijet_mInv_llr       0.359366
trijet_pt_rat_llr     3.633118
dtype: float64
	Building model ...
		Setting up architecture from yml ...
		Testing without BN ...
		With RN now ...
		Getting loss categorical_crossentropy...
Sumary of model compiled
Model: "multi_HH_ttbar_tW"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input (InputLayer)          [(None, 8)]               0

 masking_28 (Masking)        (None, 8)                 0

 normalization (Normalizati  (None, 8)                 0
 on)

 layer_0 (Dense)             (None, 16)                144

 output (Dense)              (None, 3)                 51

=================================================================
Total params: 195 (780.00 Byte)
Trainable params: 195 (780.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
	Training model ...
Epoch 1/2
1089/1089 [==============================] - 5s 3ms/step - loss: 14.8836 - accuracy: 0.8334 - precision: 0.8475 - recall: 0.6550 - auc_roc: 0.9164 - auc_pr: 0.7981 - f1_score_macro: 0.3290 - f1_score_micro: 0.8334 - precision_HH: 0.0038 - recall_HH: 5.0916e-04 - precision_ttbar: 0.8568 - recall_ttbar: 0.7621 - precision_tW: 0.3038 - recall_tW: 0.0267 - val_loss: 11.0829 - val_accuracy: 0.8445 - val_precision: 0.8450 - val_recall: 0.8311 - val_auc_roc: 0.9253 - val_auc_pr: 0.8094 - val_f1_score_macro: 0.3330 - val_f1_score_micro: 0.8445 - val_precision_HH: 0.0000e+00 - val_recall_HH: 0.0000e+00 - val_precision_ttbar: 0.8582 - val_recall_ttbar: 0.9649 - val_precision_tW: 0.2975 - val_recall_tW: 0.0481 - lr: 0.0010
Epoch 2/2
1089/1089 [==============================] - 2s 2ms/step - loss: 12.9826 - accuracy: 0.8476 - precision: 0.8486 - recall: 0.8282 - auc_roc: 0.9261 - auc_pr: 0.8147 - f1_score_macro: 0.3326 - f1_score_micro: 0.8476 - precision_HH: 0.0000e+00 - recall_HH: 0.0000e+00 - precision_ttbar: 0.8590 - recall_ttbar: 0.9620 - precision_tW: 0.3326 - recall_tW: 0.0434 - val_loss: 11.5096 - val_accuracy: 0.8526 - val_precision: 0.8538 - val_recall: 0.8276 - val_auc_roc: 0.9319 - val_auc_pr: 0.8347 - val_f1_score_macro: 0.3302 - val_f1_score_micro: 0.8526 - val_precision_HH: 0.0000e+00 - val_recall_HH: 0.0000e+00 - val_precision_ttbar: 0.8588 - val_recall_ttbar: 0.9629 - val_precision_tW: 0.4446 - val_recall_tW: 0.0360 - lr: 0.0010

Could not search for non-variable resources. Concrete function internal representation may have changed.

	Saving model info ...

2024-10-19 01:57:09.326505: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 01:57:09.326622: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2024-10-19 01:57:09.401344: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 01:57:09.401616: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session

In [94]:
DNN = DNNModel(model_config=model_config, modeldir= NOTEBOOKSDIR/'model_p9999_2')
DNN.mask_value = 9999
DNN.Run(preprocessed_df_v3, fixed_random_seed=True)

Initializing model: multi_HH_ttbar_tW
Process_HH_bbWW
Total sum of genWeights for HH_bbWW: 108.30008697509766
Total sum of sample_weights for HH_bbWW: 1857345.9098510742
Process_ttbar
Total sum of genWeights for ttbar: 381467648.0
Total sum of sample_weights for ttbar: 14858771.06210621
Process_tW
Total sum of genWeights for tW: 8042688.5
Total sum of sample_weights for tW: 7429384.208231437
	Model dataframe:
            event   genWeight  bjet0_pt_llr  bjets_dEta_llr  bjets_dPhi_llr  bjets_dR_llr  bjets_mbb_llr  mjj_llr  trijet_mInv_llr  trijet_pt_rat_llr  sample_weight  Class_HH  Class_ttbar  Class_tW
186577         18    3.805950        -0.278           0.401           0.742         1.496          1.167    0.428            0.439              0.014       3.515723         0            0         1
13167          32    0.033119        -0.242           0.329           0.937         1.507          0.849    0.393            0.549              1.259     567.997559         1            0         0
706510         36   81.103897        -0.322          -0.791          -1.330        -2.183         -2.512   -0.028            0.317             -0.649       3.159125         0            1         0
13168          42    0.033119         0.132           0.239           1.084         1.504          0.714    0.130            0.117             -0.098     567.997559         1            0         0
11905          58    0.033119         0.109           0.358           0.747         1.493          1.051   -0.491            0.396             -0.674     567.997559         1            0         0
...           ...         ...           ...             ...             ...           ...            ...      ...              ...                ...            ...       ...          ...       ...
1383502  79999662  337.046997        -0.233           0.350           0.384         1.533         -0.991    0.068            0.271              0.563      13.128513         0            1         0
1307638  79999672  337.046997         0.245           0.164          -0.629        -0.645          1.120   -0.184            0.389             -0.204      13.128513         0            1         0
906730   79999852  337.046997        -0.260           0.304          -1.322        -1.059         -0.895   -0.244           -0.445             -0.733      13.128513         0            1         0
1241332  79999874  337.046997         0.015        9999.000          -1.392        -3.735         -4.007   -0.444            0.435             -0.073      13.128513         0            1         0
1583489  79999908  337.046997        -0.263           0.344          -1.614        -1.566          1.186    0.403           -0.394             -0.151      13.128513         0            1         0

[1857346 rows x 14 columns]
	Preprocessing input ...
	mask value isss 9999
Mean: bjet0_pt_llr        -0.105481
bjets_dEta_llr      -0.407105
bjets_dPhi_llr      -0.534035
bjets_dR_llr        -0.712892
bjets_mbb_llr       -2.883128
mjj_llr             -0.065720
trijet_mInv_llr     -0.058991
trijet_pt_rat_llr   -0.365355
dtype: float64
Variance: bjet0_pt_llr          1.187154
bjets_dEta_llr        4.008633
bjets_dPhi_llr        3.319234
bjets_dR_llr          2.244745
bjets_mbb_llr        38.473088
mjj_llr               0.106370
trijet_mInv_llr       0.359366
trijet_pt_rat_llr     3.633118
dtype: float64
	Building model ...
		Setting up architecture from yml ...
		Testing without BN ...
		With RN now ...
		Getting loss categorical_crossentropy...
Sumary of model compiled
Model: "multi_HH_ttbar_tW"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input (InputLayer)          [(None, 8)]               0

 masking_29 (Masking)        (None, 8)                 0

 normalization (Normalizati  (None, 8)                 0
 on)

 layer_0 (Dense)             (None, 16)                144

 output (Dense)              (None, 3)                 51

=================================================================
Total params: 195 (780.00 Byte)
Trainable params: 195 (780.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
	Training model ...
Epoch 1/2
1089/1089 [==============================] - 5s 3ms/step - loss: 14.8836 - accuracy: 0.8334 - precision: 0.8475 - recall: 0.6550 - auc_roc: 0.9164 - auc_pr: 0.7981 - f1_score_macro: 0.3290 - f1_score_micro: 0.8334 - precision_HH: 0.0038 - recall_HH: 5.0916e-04 - precision_ttbar: 0.8568 - recall_ttbar: 0.7621 - precision_tW: 0.3038 - recall_tW: 0.0267 - val_loss: 11.0829 - val_accuracy: 0.8445 - val_precision: 0.8450 - val_recall: 0.8311 - val_auc_roc: 0.9253 - val_auc_pr: 0.8094 - val_f1_score_macro: 0.3330 - val_f1_score_micro: 0.8445 - val_precision_HH: 0.0000e+00 - val_recall_HH: 0.0000e+00 - val_precision_ttbar: 0.8582 - val_recall_ttbar: 0.9649 - val_precision_tW: 0.2975 - val_recall_tW: 0.0481 - lr: 0.0010
Epoch 2/2
1089/1089 [==============================] - 3s 2ms/step - loss: 12.9826 - accuracy: 0.8476 - precision: 0.8486 - recall: 0.8282 - auc_roc: 0.9261 - auc_pr: 0.8147 - f1_score_macro: 0.3326 - f1_score_micro: 0.8476 - precision_HH: 0.0000e+00 - recall_HH: 0.0000e+00 - precision_ttbar: 0.8590 - recall_ttbar: 0.9620 - precision_tW: 0.3326 - recall_tW: 0.0434 - val_loss: 11.5096 - val_accuracy: 0.8526 - val_precision: 0.8538 - val_recall: 0.8276 - val_auc_roc: 0.9319 - val_auc_pr: 0.8347 - val_f1_score_macro: 0.3302 - val_f1_score_micro: 0.8526 - val_precision_HH: 0.0000e+00 - val_recall_HH: 0.0000e+00 - val_precision_ttbar: 0.8588 - val_recall_ttbar: 0.9629 - val_precision_tW: 0.4446 - val_recall_tW: 0.0360 - lr: 0.0010

Could not search for non-variable resources. Concrete function internal representation may have changed.

	Saving model info ...

2024-10-19 01:57:22.805888: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 01:57:22.806039: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2024-10-19 01:57:22.878795: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2024-10-19 01:57:22.878924: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session